GUIAS = [
    {
        'id': 'papa', 'nombre': 'Papa', 'icono': '🥔',
        'descripcion': 'La papa es un tubérculo de gran importancia alimenticia a nivel mundial. Se cultiva en regiones templadas y frías de los Andes peruanos.',
        'categoria': 'Tubérculos',
        'temporada': 'Agosto - Diciembre (siembra), Enero - Abril (cosecha)',
        'clima': 'Templado a frío, 12-18°C. Sensible a heladas.',
        'suelo': 'Franco-arenoso, profundo, bien drenado. pH 5.5-6.5.',
        'riego': 'Cada 3-4 días en crecimiento. Reducir en maduración.',
        'fertilizante': 'NPK 10-10-10 al inicio. Alto en potasio en tuberización.',
        'nutrientes': 'Nitrógeno (N), Fósforo (P), Potasio (K), Magnesio (Mg), Azufre (S)',
        'plagas': ['Gusano de la papa', 'Polilla de la papa', 'Pulgones', 'Nematodos'],
        'enfermedades': ['Tizón tardío', 'Tizón temprano', 'Sarna común'],
        'prevencion': 'Rotación de cultivos cada 3 años. Usar semilla certificada. Evitar exceso de humedad.',
        'consejos': ['Siembra en luna llena para mejor desarrollo radicular.', 'Aporca los tubérculos cada 20 días.', 'No riegues por aspersión en temporada de lluvias.']
    },
    {
        'id': 'tomate', 'nombre': 'Tomate', 'icono': '🍅',
        'descripcion': 'El tomate es una hortaliza versátil cultivada en invernaderos y campo abierto. Requiere cuidados específicos para evitar enfermedades fúngicas.',
        'categoria': 'Hortalizas',
        'temporada': 'Septiembre - Febrero',
        'clima': 'Cálido, 20-30°C. No tolera heladas.',
        'suelo': 'Franco, rico en materia orgánica. pH 6.0-6.8.',
        'riego': 'Riego por goteo diario en verano. Evitar mojar hojas.',
        'fertilizante': 'NPK 15-15-15 cada 15 días. Calcio para evitar pudrición apical.',
        'nutrientes': 'Nitrógeno (N), Fósforo (P), Potasio (K), Calcio (Ca), Magnesio (Mg)',
        'plagas': ['Mosca blanca', 'Pulgones', 'Araña roja', 'Trips'],
        'enfermedades': ['Tizón tardío', 'Tizón temprano', 'Moho foliar', 'Mancha septoriosa'],
        'prevencion': 'Tutoreo desde los 15 días. Poda hojas inferiores. Ventilación en invernadero.',
        'consejos': ['Usa mallas anti-áfidos en invernadero.', 'Poda los brotes laterales (chupones).', 'Mantén el suelo cubierto con mulch plástico.']
    },
    {
        'id': 'maiz', 'nombre': 'Maíz', 'icono': '🌽',
        'descripcion': 'El maíz es un cereal fundamental en la alimentación andina. Se cultiva extensivamente en la sierra y costa peruana.',
        'categoria': 'Cereales',
        'temporada': 'Octubre - Marzo',
        'clima': 'Cálido a templado, 18-30°C.',
        'suelo': 'Franco, profundo, con buen drenaje. pH 5.5-7.0.',
        'riego': 'Cada 5-7 días. Crítico en floración y llenado de grano.',
        'fertilizante': 'NPK 20-10-10 al inicio. Urea en crecimiento vegetativo.',
        'nutrientes': 'Nitrógeno (N), Fósforo (P), Potasio (K), Zinc (Zn), Boro (B)',
        'plagas': ['Cogollero', 'Gusano mazorquero', 'Pulgón del maíz'],
        'enfermedades': ['Mancha gris', 'Roya común', 'Tizón foliar'],
        'prevencion': 'Rotación con leguminosas. Densidad de siembra adecuada. Control de malezas.',
        'consejos': ['Siembra en hileras orientadas norte-sur.', 'Aporca a los 30 días para fijar raíces.', 'Cosecha cuando el grano esté lechoso para choclo.']
    },
    {
        'id': 'cafe', 'nombre': 'Café', 'icono': '☕',
        'descripcion': 'El café es uno de los cultivos de mayor valor comercial en el mundo. Perú produce cafés especiales de alta calidad en regiones de selva alta.',
        'categoria': 'Cultivos comerciales',
        'temporada': 'Marzo - Junio (cosecha principal)',
        'clima': 'Subtropical, 18-24°C. Sombra parcial recomendada.',
        'suelo': 'Franco-arcilloso, ácido. pH 5.0-6.0. Rico en materia orgánica.',
        'riego': 'Moderado. Crítico en floración y llenado de frutos.',
        'fertilizante': 'NPK 15-5-20. Rico en potasio para calidad de taza.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Boro (B), Zinc (Zn)',
        'plagas': ['Broca del café', 'Minador de la hoja', 'Arañita roja'],
        'enfermedades': ['Roya del cafeto', 'Ojo de gallo', 'Mal de hilachas'],
        'prevencion': 'Mantener sombra adecuada (25-40%). Poda sanitaria anual. Renovación de cafetos cada 5-7 años.',
        'consejos': ['El café de altura (1200-1800 msnm) tiene mejor calidad de taza.', 'Fermenta los granos entre 18-24 horas para café lavado.', 'Siembra plátanos como sombra temporal en los primeros años.']
    },
    {
        'id': 'palta', 'nombre': 'Palta (Aguacate)', 'icono': '🥑',
        'descripcion': 'La palta o aguacate es un fruto tropical de alto valor nutricional y gran demanda comercial. Perú es uno de los principales exportadores mundiales.',
        'categoria': 'Frutales',
        'temporada': 'Febrero - Setiembre (según variedad)',
        'clima': 'Templado-cálido, 15-28°C. Sensible a heladas y vientos fuertes.',
        'suelo': 'Franco, profundo (>1m), bien drenado. pH 5.5-6.5.',
        'riego': 'Riego por goteo cada 2-3 días en verano. Reducir en invierno.',
        'fertilizante': 'NPK 10-20-20. Alto en potasio y fósforo.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Zinc (Zn), Boro (B)',
        'plagas': ['Arañita roja', 'Trips', 'Barrenador del fruto'],
        'enfermedades': ['Tristeza del aguacate', 'Mancha negra', 'Pudrición de raíz'],
        'prevencion': 'Usar portainjertos resistentes a Phytophthora. Evitar encharcamiento. Poda de formación.',
        'consejos': ['La variedad Hass es la más comercial.', 'Los árboles tardan 3-4 años en producir.', 'El acolchado orgánico ayuda a mantener la humedad del suelo.']
    },
    {
        'id': 'arroz', 'nombre': 'Arroz', 'icono': '🌾',
        'descripcion': 'El arroz es un cereal básico en la alimentación peruana. Se cultiva principalmente en la costa norte bajo sistema de inundación.',
        'categoria': 'Cereales',
        'temporada': 'Enero - Mayo (costa norte)',
        'clima': 'Cálido, 22-32°C. Alta humedad relativa.',
        'suelo': 'Franco-arcilloso, capacidad de retención de agua. pH 5.5-6.5.',
        'riego': 'Inundación permanente (5-10 cm de agua) durante todo el ciclo.',
        'fertilizante': 'NPK 20-10-10. Urea en macollamiento y primordio.',
        'nutrientes': 'Nitrógeno (N), Fósforo (P), Potasio (K), Zinc (Zn), Silicio (Si)',
        'plagas': ['Cogollero del arroz', 'Sogata', 'Barrenador del tallo'],
        'enfermedades': ['Quemado del arroz', 'Mancha de la hoja', 'Pudrición del tallo'],
        'prevencion': 'Nivelación precisa del terreno. Drenaje intermitente en macollamiento. Variedades resistentes.',
        'consejos': ['Drena el arrozal 10 días antes de la cosecha.', 'Usa semilla certificada de la variedad Esperanza o La 65.', 'El encalado mejora la disponibilidad de nutrientes en suelos ácidos.']
    },
    {
        'id': 'fresa', 'nombre': 'Fresa', 'icono': '🍓',
        'descripcion': 'La fresa es un cultivo de alto valor comercial que se produce principalmente en los valles interandinos y costa central del Perú.',
        'categoria': 'Frutales',
        'temporada': 'Mayo - Octubre',
        'clima': 'Templado, 15-25°C. Requiere horas frío para buena producción.',
        'suelo': 'Franco-arenoso, suelto. pH 5.5-6.5. Alto en materia orgánica.',
        'riego': 'Riego por goteo diario en verano. Evitar mojar frutos.',
        'fertilizante': 'NPK 12-12-17 con micronutrientes. Aplicar cada 7-10 días.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Calcio (Ca), Boro (B)',
        'plagas': ['Arañita roja', 'Pulgones', 'Trips', 'Babosas'],
        'enfermedades': ['Quemadura foliar', 'Moho gris', 'Pudrición de raíz'],
        'prevencion': 'Usar acolchado plástico. Plantas certificadas libres de virus. Renovar plantación cada 2 años.',
        'consejos': ['El acolchado plástico plateado repele pulgones.', 'Los estolones deben eliminarse si no se busca propagación.', 'La fresa responde muy bien a la fertirrigación.']
    },
    {
        'id': 'vid', 'nombre': 'Vid', 'icono': '🍇',
        'descripcion': 'La vid es cultivada en la costa peruana para producción de uva de mesa y pisco. Perú es un importante exportador de uva de mesa.',
        'categoria': 'Frutales',
        'temporada': 'Julio - Diciembre (uva de mesa)',
        'clima': 'Cálido-seco, 18-30°C. Requiere horas frío en invierno.',
        'suelo': 'Franco-arenoso, profundo, con buen drenaje. pH 6.0-7.5.',
        'riego': 'Riego por goteo cada 3-5 días. Reducir en maduración.',
        'fertilizante': 'NPK 10-20-20. Alto en potasio para calidad de fruto.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Magnesio (Mg), Boro (B)',
        'plagas': ['Arañita roja', 'Trips', 'Cochinilla harinosa'],
        'enfermedades': ['Podredumbre negra', 'Yesca', 'Tizón foliar'],
        'prevencion': 'Poda de formación en los primeros años. Desinfección de herramientas de poda. Monitoreo constante.',
        'consejos': ['La variedad Quebranta es ideal para pisco.', 'El estrés hídrico controlado mejora la calidad de la uva.', 'Poda en seco después de la cosecha.']
    },
    {
        'id': 'manzano', 'nombre': 'Manzano', 'icono': '🍎',
        'descripcion': 'El manzano se cultiva en valles interandinos y sierra peruana. Requiere horas de frío para una producción óptima.',
        'categoria': 'Frutales',
        'temporada': 'Enero - Abril',
        'clima': 'Templado-frío, 10-22°C. Requiere frío invernal.',
        'suelo': 'Franco, profundo, bien drenado. pH 6.0-7.0.',
        'riego': 'Cada 5-7 días en primavera-verano. Reducir en reposo.',
        'fertilizante': 'NPK 10-20-20. Aplicar después de poda y en floración.',
        'nutrientes': 'Nitrógeno (N), Fósforo (P), Potasio (K), Calcio (Ca), Boro (B)',
        'plagas': ['Pulgón lanígero', 'Arañita roja', 'Gusano de la manzana'],
        'enfermedades': ['Sarna del manzano', 'Podredumbre negra', 'Roya'],
        'prevencion': 'Poda de renovación anual. Raleo de frutos para mejor tamaño. Fungicidas preventivos en primavera.',
        'consejos': ['Las variedades del grupo Delicious se adaptan bien a la sierra.', 'El raleo manual mejora el tamaño del fruto.', 'Aplica caldo sulfocálcico en reposo vegetativo.']
    },
    {
        'id': 'durazno', 'nombre': 'Durazno', 'icono': '🍑',
        'descripcion': 'El durazno se cultiva en los valles interandinos del Perú. Las variedades de pulpa amarilla son las más comerciales.',
        'categoria': 'Frutales',
        'temporada': 'Noviembre - Febrero',
        'clima': 'Templado, 12-24°C. Requiere frío invernal moderado.',
        'suelo': 'Franco, profundo (>80cm). pH 6.0-6.5.',
        'riego': 'Cada 4-6 días en producción. Evitar estrés hídrico en llenado de fruto.',
        'fertilizante': 'NPK 10-20-20. Aplicar nitrógeno en brotación y potasio en engorde.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Calcio (Ca), Boro (B)',
        'plagas': ['Anarsia', 'Pulgón verde', 'Mosca de la fruta'],
        'enfermedades': ['Mancha bacterial', 'Oídio', 'Podredumbre parda'],
        'prevencion': 'Poda de formación en vaso abierto. Control de mosca de la fruta con trampas. Raleo de frutos.',
        'consejos': ['La variedad Huayco Rojo es tradicional peruana.', 'El aclareo de frutos mejora el calibre.', 'Aplica cobre en caída de hojas para prevenir infecciones.']
    },
    {
        'id': 'naranjo', 'nombre': 'Naranjo', 'icono': '🍊',
        'descripcion': 'Los cítricos se cultivan en la selva alta y costa norte del Perú. La naranja es la fruta de mayor producción nacional.',
        'categoria': 'Frutales',
        'temporada': 'Mayo - Noviembre',
        'clima': 'Cálido, 20-30°C. Sensible a heladas.',
        'suelo': 'Franco-arenoso, profundo. pH 5.5-6.5.',
        'riego': 'Cada 4-7 días. Crítico en floración y cuajado de frutos.',
        'fertilizante': 'NPK 15-5-20. Rico en potasio para calidad de jugo.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Magnesio (Mg), Zinc (Zn)',
        'plagas': ['Mosca blanca', 'Pulgones', 'Minador de la hoja'],
        'enfermedades': ['HLB (Huanglongbing)', 'Mancha grasienta', 'Tristeza'],
        'prevencion': 'Control de vectores (psílidos). Material vegetal certificado. Barreras vivas alrededor del huerto.',
        'consejos': ['El portainjerto patrón trifolio es tolerante a suelos alcalinos.', 'La poda de formación en los primeros 3 años es crucial.', 'Los cítricos requieren aplicación foliar de zinc y manganeso.']
    },
    {
        'id': 'pimiento', 'nombre': 'Pimiento', 'icono': '🌶️',
        'descripcion': 'El pimiento se cultiva en la costa peruana, principalmente bajo riego por goteo y acolchado plástico.',
        'categoria': 'Hortalizas',
        'temporada': 'Agosto - Diciembre',
        'clima': 'Cálido, 18-28°C. No tolera heladas ni temperaturas extremas.',
        'suelo': 'Franco, suelto, bien drenado. pH 6.0-6.8.',
        'riego': 'Riego por goteo diario en verano. Evitar estrés hídrico.',
        'fertilizante': 'NPK 12-12-17. Aplicar potasio en floración y llenado de frutos.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Calcio (Ca), Magnesio (Mg)',
        'plagas': ['Pulgones', 'Trips', 'Arañita roja', 'Mosca blanca'],
        'enfermedades': ['Mancha bacterial', 'Oídio', 'Podredumbre de raíz'],
        'prevencion': 'Rotación con no solanáceas. Semillas certificadas. Riego por goteo para evitar salpicaduras.',
        'consejos': ['El tutoreo mejora la calidad del fruto.', 'Usa acolchado plástico plateado para repeler trips.', 'La cosecha continua estimula nueva producción.']
    },
    {
        'id': 'frijol', 'nombre': 'Frijol', 'icono': '🫘',
        'descripcion': 'El frijol es una leguminosa importante en la dieta peruana. Mejora la fertilidad del suelo al fijar nitrógeno atmosférico.',
        'categoria': 'Legumbres',
        'temporada': 'Setiembre - Diciembre (costa), Diciembre - Marzo (sierra)',
        'clima': 'Templado a cálido, 15-25°C.',
        'suelo': 'Franco, suelto, bien drenado. pH 5.5-7.0.',
        'riego': 'Cada 4-6 días. Crítico en floración y llenado de vainas.',
        'fertilizante': 'NPK 10-30-10. Bajo en nitrógeno (fijan su propio N).',
        'nutrientes': 'Fósforo (P), Potasio (K), Magnesio (Mg), Molibdeno (Mo), Cobalto (Co)',
        'plagas': ['Mosca minadora', 'Pulgón negro', 'Orugas'],
        'enfermedades': ['Roya del frijol', 'Antracnosis', 'Mancha angular'],
        'prevencion': 'Rotación de cultivos. Inoculación con Rhizobium. Densidad de siembra adecuada.',
        'consejos': ['Inocula la semilla con Rhizobium para mejorar la fijación de nitrógeno.', 'El frijol no debe sembrarse después de otras leguminosas.', 'Cosecha cuando las vainas estén amarillas y los granos duros.']
    },
    {
        'id': 'zanahoria', 'nombre': 'Zanahoria', 'icono': '🥕',
        'descripcion': 'La zanahoria es una hortaliza de raíz cultivada en la sierra y costa peruana. Rica en betacaroteno y vitaminas.',
        'categoria': 'Hortalizas',
        'temporada': 'Marzo - Agosto (sierra), Junio - Noviembre (costa)',
        'clima': 'Templado-frío, 12-20°C.',
        'suelo': 'Franco-arenoso, profundo, suelto. pH 6.0-6.8.',
        'riego': 'Cada 3-5 días. Uniforme para evitar raíces deformes.',
        'fertilizante': 'NPK 15-15-15. Alto en potasio para desarrollo radicular.',
        'nutrientes': 'Potasio (K), Fósforo (P), Boro (B), Calcio (Ca)',
        'plagas': ['Mosca de la zanahoria', 'Pulgones', 'Nematodos'],
        'enfermedades': ['Mancha foliar', 'Podredumbre blanda', 'Oídio'],
        'prevencion': 'Suelos sueltos sin piedras. Riego uniforme. Rotación con brassicáceas.',
        'consejos': ['El exceso de nitrógeno causa raíces bifurcadas.', 'La cosecha se realiza entre 90-120 días según variedad.', 'El mulching mejora la uniformidad del color de la raíz.']
    },
    {
        'id': 'lechuga', 'nombre': 'Lechuga', 'icono': '🥬',
        'descripcion': 'La lechuga es una hortaliza de hoja de rápido crecimiento. Se cultiva principalmente en huertos urbanos y viveros.',
        'categoria': 'Hortalizas',
        'temporada': 'Todo el año (con protección)',
        'clima': 'Templado, 12-22°C. Sensible al calor extremo.',
        'suelo': 'Franco, suelto, rico en materia orgánica. pH 6.0-7.0.',
        'riego': 'Riego ligero diario. Mantener humedad constante.',
        'fertilizante': 'NPK 10-10-10. Alto en nitrógeno para crecimiento foliar.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Calcio (Ca), Hierro (Fe)',
        'plagas': ['Pulgones', 'Trips', 'Babosas y caracoles'],
        'enfermedades': ['Mildiú', 'Podredumbre blanda', 'Mancha de la hoja'],
        'prevencion': 'Densidad de siembra adecuada. Riego por goteo. Rotación corta (15-20 días entre camas).',
        'consejos': ['Siembra en camas elevadas para mejor drenaje.', 'La lechuga crespa es más resistente al calor que la lechuga americana.', 'Cosecha temprano en la mañana para mejor textura.']
    },
    {
        'id': 'cebolla', 'nombre': 'Cebolla', 'icono': '🧅',
        'descripcion': 'La cebolla es una hortaliza de bulbo fundamental en la cocina peruana. Se cultiva en la costa y sierra del país.',
        'categoria': 'Hortalizas',
        'temporada': 'Mayo - Diciembre',
        'clima': 'Templado, 15-25°C. Requiere días largos para bulbificación.',
        'suelo': 'Franco, suelto, bien drenado. pH 6.0-6.8.',
        'riego': 'Cada 3-5 días. Suspender 15 días antes de cosecha.',
        'fertilizante': 'NPK 12-12-17. Alto en potasio para engorde de bulbo.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Fósforo (P), Azufre (S)',
        'plagas': ['Trips', 'Mosca de la cebolla', 'Gusanos del suelo'],
        'enfermedades': ['Podredumbre blanda', 'Mancha púrpura', 'Mildiú'],
        'prevencion': 'Rotación de cultivos por 3 años. Semillas certificadas. Drenaje adecuado.',
        'consejos': ['Dobla el cuello de la cebolla 15 días antes de cosechar.', 'El azufre mejora el sabor y conservación del bulbo.', 'Almacena en lugar fresco y seco con buena ventilación.']
    },
    {
        'id': 'brocoli', 'nombre': 'Brócoli', 'icono': '🥦',
        'descripcion': 'El brócoli es una crucífera rica en vitaminas y antioxidantes. Se cultiva en valles interandinos y costa central.',
        'categoria': 'Hortalizas',
        'temporada': 'Febrero - Junio (sierra), Mayo - Setiembre (costa)',
        'clima': 'Templado-frío, 12-20°C.',
        'suelo': 'Franco, profundo, rico en materia orgánica. pH 6.0-7.0.',
        'riego': 'Cada 3-4 días. Uniforme para cabezas compactas.',
        'fertilizante': 'NPK 15-15-15. Alto en nitrógeno y potasio.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Calcio (Ca), Magnesio (Mg), Boro (B)',
        'plagas': ['Pulgones', 'Orugas', 'Mosca blanca'],
        'enfermedades': ['Mancha foliar', 'Podredumbre negra', 'Hernia de las crucíferas'],
        'prevencion': 'Rotación con no crucíferas. Suelo con buen drenaje. Control de malezas.',
        'consejos': ['La cosecha se realiza cuando la cabeza está compacta y antes de que florezca.', 'Aplica boro para evitar tallos huecos.', 'Las cabezas laterales aparecen después de cortar la principal.']
    },
    {
        'id': 'espinaca', 'nombre': 'Espinaca', 'icono': '🌿',
        'descripcion': 'La espinaca es una hortaliza de hoja verde rica en hierro y vitaminas. De rápido crecimiento y alta demanda.',
        'categoria': 'Hortalizas',
        'temporada': 'Marzo - Setiembre',
        'clima': 'Templado-frío, 10-20°C. Sensible al calor.',
        'suelo': 'Franco-arenoso, rico en materia orgánica. pH 6.5-7.5.',
        'riego': 'Riego ligero frecuente. Mantener humedad constante.',
        'fertilizante': 'NPK 10-10-10. Alto en nitrógeno para hojas grandes.',
        'nutrientes': 'Nitrógeno (N), Hierro (Fe), Calcio (Ca), Magnesio (Mg)',
        'plagas': ['Pulgones', 'Minador de la hoja', 'Babosas'],
        'enfermedades': ['Mildiú', 'Mancha foliar', 'Podredumbre de raíz'],
        'prevencion': 'Densidad de siembra adecuada. Riego por goteo. Variedades resistentes al mildiú.',
        'consejos': ['Cosecha las hojas exteriores dejando el centro para seguir produciendo.', 'La espinaca se debe lavar cuidadosamente por la arena.', 'Siembra escalonada cada 15 días para cosecha continua.']
    },
    {
        'id': 'acelga', 'nombre': 'Acelga', 'icono': '🌱',
        'descripcion': 'La acelga es una hortaliza de hoja resistente y fácil de cultivar. Produce durante todo el año en climas templados.',
        'categoria': 'Hortalizas',
        'temporada': 'Todo el año',
        'clima': 'Templado, 12-25°C. Tolera calor moderado.',
        'suelo': 'Franco, profundo, rico en materia orgánica. pH 6.0-7.5.',
        'riego': 'Cada 3-4 días. Aumentar en verano.',
        'fertilizante': 'NPK 10-10-10. Aplicar compost cada 30 días.',
        'nutrientes': 'Nitrógeno (N), Potasio (K), Magnesio (Mg), Hierro (Fe)',
        'plagas': ['Pulgones', 'Minador', 'Babosas'],
        'enfermedades': ['Mancha foliar', 'Podredumbre', 'Roya'],
        'prevencion': 'Rotación de cultivos. Espaciamiento adecuado. Eliminar hojas viejas.',
        'consejos': ['Cosecha las hojas externas a partir de 60 días.', 'Los tallos de colores (amarillo, naranja, rojo) son más decorativos.', 'Responde muy bien al abono orgánico líquido cada 15 días.']
    },
    {
        'id': 'quinua', 'nombre': 'Quinua', 'icono': '🌾',
        'descripcion': 'La quinua es un pseudocereal andino de alto valor nutricional. Perú es uno de los principales productores mundiales.',
        'categoria': 'Andinos',
        'temporada': 'Setiembre - Diciembre (siembra), Abril - Junio (cosecha)',
        'clima': 'Frío a templado, 5-20°C. Tolera heladas moderadas.',
        'suelo': 'Franco-arenoso, bien drenado. pH 6.0-7.5.',
        'riego': 'Cada 5-7 días. Crítico en floración y llenado de grano.',
        'fertilizante': 'NPK 10-10-10. Evitar exceso de nitrógeno (acama).',
        'nutrientes': 'Nitrógeno (N), Fósforo (P), Potasio (K), Calcio (Ca), Zinc (Zn)',
        'plagas': ['Kcona kcona', 'Pulgones', 'Gusano cortador'],
        'enfermedades': ['Mildiú', 'Mancha foliar', 'Podredumbre marrón'],
        'prevencion': 'Semilla certificada. Rotación con papáceas. Control de malezas temprano.',
        'consejos': ['La quinua real del altiplano tiene grano más grande.', 'El lavado del grano elimina las saponinas amargas.', 'Siembra en surcos con orientación este-oeste para mayor insolación.']
    },
    {
        'id': 'camote', 'nombre': 'Camote', 'icono': '🍠',
        'descripcion': 'El camote o batata es una raíz tuberosa de gran valor energético. Se cultiva en la costa y selva peruana.',
        'categoria': 'Tubérculos',
        'temporada': 'Todo el año (costa), Octubre - Marzo (selva)',
        'clima': 'Cálido, 20-30°C. No tolera heladas.',
        'suelo': 'Franco-arenoso, suelto. pH 5.5-6.8.',
        'riego': 'Cada 5-7 días. Reducir en maduración.',
        'fertilizante': 'NPK 5-10-20. Alto en potasio para desarrollo de raíces.',
        'nutrientes': 'Potasio (K), Fósforo (P), Calcio (Ca), Magnesio (Mg)',
        'plagas': ['Gusano de la raíz', 'Pulgones', 'Mosca blanca'],
        'enfermedades': ['Podredumbre blanda', 'Mancha foliar', 'Virus del mosaico'],
        'prevencion': 'Esquejes certificados. Rotación con gramíneas. Control de malezas.',
        'consejos': ['Las variedades de pulpa anaranjada tienen más betacaroteno.', 'La cosecha se realiza a los 4-5 meses.', 'El curado a 30°C mejora la conservación postcosecha.']
    },
    {
        'id': 'yuca', 'nombre': 'Yuca', 'icono': '🌿',
        'descripcion': 'La yuca o mandioca es un arbusto cuyas raíces son fuente importante de carbohidratos. Cultivo tradicional de la selva peruana.',
        'categoria': 'Tubérculos',
        'temporada': 'Enero - Junio',
        'clima': 'Cálido-húmedo, 22-32°C.',
        'suelo': 'Franco-arenoso, suelto. pH 5.0-6.5. Tolerante a suelos pobres.',
        'riego': 'Moderado. Tolera sequía una vez establecida.',
        'fertilizante': 'NPK 10-10-10. Alto en potasio para raíces.',
        'nutrientes': 'Potasio (K), Nitrógeno (N), Fósforo (P), Calcio (Ca), Magnesio (Mg)',
        'plagas': ['Ácaro verde', 'Mosca blanca', 'Cochinilla'],
        'enfermedades': ['Mosaico de la yuca', 'Podredumbre de raíz', 'Mancha foliar'],
        'prevencion': 'Esquejes de plantas sanas. Rotación prolongada. Variedades resistentes.',
        'consejos': ['La yuca amarga requiere procesamiento para eliminar cianuro.', 'El suelo arenoso facilita la cosecha de raíces.', 'Se puede asociar con maíz y frijol en sistemas milpa.']
    },
    {
        'id': 'platano', 'nombre': 'Plátano', 'icono': '🍌',
        'descripcion': 'El plátano es una de las frutas más consumidas en el Perú. Se cultiva principalmente en la selva y costa norte.',
        'categoria': 'Frutales',
        'temporada': 'Todo el año',
        'clima': 'Cálido-húmedo, 22-30°C. No tolera heladas ni vientos fuertes.',
        'suelo': 'Franco, profundo (>1m), rico en materia orgánica. pH 5.5-7.0.',
        'riego': 'Riego cada 3-4 días en verano. Mantener suelo húmedo.',
        'fertilizante': 'NPK 15-5-25. Alto en potasio para calidad del fruto.',
        'nutrientes': 'Potasio (K), Nitrógeno (N), Magnesio (Mg), Calcio (Ca)',
        'plagas': ['Picudo negro', 'Nemátodos', 'Trips de la mancha roja'],
        'enfermedades': ['Sigatoka negra', 'Mal de Panamá', 'Moko del plátano'],
        'prevencion': 'Material vegetal certificado. Deshoje sanitario. Drenaje adecuado.',
        'consejos': ['El plátano de seda es el más consumido en Perú.', 'Los hijuelos se seleccionan a los 3-4 meses.', 'El racimo se cosecha cuando los frutos están llenos pero aún verdes.']
    },
    {
        'id': 'mango', 'nombre': 'Mango', 'icono': '🥭',
        'descripcion': 'El mango es una fruta tropical de alta demanda comercial. Perú exporta principalmente la variedad Kent a mercados internacionales.',
        'categoria': 'Frutales',
        'temporada': 'Noviembre - Marzo',
        'clima': 'Cálido-seco, 22-32°C. Requiere periodo seco para floración.',
        'suelo': 'Franco, profundo. pH 5.5-7.0. Tolera suelos calcáreos.',
        'riego': 'Riego por goteo cada 3-5 días. Suspender antes de floración.',
        'fertilizante': 'NPK 15-5-20. Alto en potasio para calidad del fruto.',
        'nutrientes': 'Potasio (K), Nitrógeno (N), Fósforo (P), Calcio (Ca), Boro (B)',
        'plagas': ['Mosca de la fruta', 'Trips', 'Arañita roja'],
        'enfermedades': ['Antracnosis', 'Oídio', 'Mancha bacterial'],
        'prevencion': 'Poda de formación y saneamiento. Control de mosca con trampas. Fungicidas en floración.',
        'consejos': ['La madurez se percibe por el aroma y ligero ablandamiento.', 'No almacenes mangos en refrigeración por debajo de 10°C.', 'El estrés hídrico controlado induce la floración del mango.']
    },
    {
        'id': 'papaya', 'nombre': 'Papaya', 'icono': '🍈',
        'descripcion': 'La papaya es una fruta tropical de rápido crecimiento. Se cultiva en la selva baja y costa norte del Perú.',
        'categoria': 'Frutales',
        'temporada': 'Todo el año',
        'clima': 'Cálido-húmedo, 22-30°C. Sensible a heladas y vientos.',
        'suelo': 'Franco-arenoso, suelto, bien drenado. pH 5.5-6.5.',
        'riego': 'Cada 2-3 días. No tolera encharcamiento.',
        'fertilizante': 'NPK 15-5-20. Alto en potasio para frutos dulces.',
        'nutrientes': 'Potasio (K), Nitrógeno (N), Magnesio (Mg), Zinc (Zn)',
        'plagas': ['Mosca blanca', 'Pulgones', 'Arañita roja'],
        'enfermedades': ['Mancha anular', 'Oídio', 'Podredumbre de raíz'],
        'prevencion': 'Plantas certificadas. Rotación de cultivos. Control de vectores de virus.',
        'consejos': ['Las plantas pueden ser macho, hembra o hermafroditas.', 'La papaya hermafrodita produce frutos alargados más comerciales.', 'Renueva la plantación cada 3 años.']
    },
    {
        'id': 'granadilla', 'nombre': 'Granadilla', 'icono': '🍊',
        'descripcion': 'La granadilla es una fruta andina de sabor dulce y aroma agradable. Se cultiva en valles interandinos entre 1500-2500 msnm.',
        'categoria': 'Frutales',
        'temporada': 'Marzo - Agosto',
        'clima': 'Templado-cálido, 15-24°C. Sin heladas.',
        'suelo': 'Franco, profundo, bien drenado. pH 5.5-7.0.',
        'riego': 'Cada 3-5 días. Sensible a sequía en floración.',
        'fertilizante': 'NPK 10-15-15. Alto en potasio y fósforo para floración.',
        'nutrientes': 'Potasio (K), Fósforo (P), Nitrógeno (N), Boro (B)',
        'plagas': ['Mosca de la fruta', 'Ácaros', 'Pulgones'],
        'enfermedades': ['Fusarium', 'Mancha foliar', 'Podredumbre del tallo'],
        'prevencion': 'Poda sanitaria. Tutoreo adecuado. Drenaje del suelo.',
        'consejos': ['La polinización manual mejora el cuajado de frutos.', 'Cosecha cuando el fruto cambia de color y se desprende fácilmente.', 'La granadilla se conserva hasta 30 días en refrigeración.']
    },
    {
        'id': 'maracuya', 'nombre': 'Maracuyá', 'icono': '🍑',
        'descripcion': 'El maracuyá o fruta de la pasión es una fruta tropical de sabor ácido intenso. Se usa para jugos y postres.',
        'categoria': 'Frutales',
        'temporada': 'Enero - Julio',
        'clima': 'Cálido, 20-30°C. Requiere buena luminosidad.',
        'suelo': 'Franco-arenoso, suelto. pH 5.5-6.5.',
        'riego': 'Cada 2-3 días en verano. Reducir en invierno.',
        'fertilizante': 'NPK 12-12-17. Alto en potasio para calidad de jugo.',
        'nutrientes': 'Potasio (K), Nitrógeno (N), Fósforo (P), Magnesio (Mg)',
        'plagas': ['Mosca blanca', 'Pulgones', 'Ácaros'],
        'enfermedades': ['Mancha bacterial', 'Podredumbre del tallo', 'Virus del mosaico'],
        'prevencion': 'Poda de formación. Espaldera o tutor. Control fitosanitario frecuente.',
        'consejos': ['La polinización por abejas mejora la producción.', 'El fruto maduro cae al suelo cuando está listo.', 'Recoge los frutos del suelo diariamente para evitar fermentación.']
    },
    {
        'id': 'cebada', 'nombre': 'Cebada', 'icono': '🌾',
        'descripcion': 'La cebada es un cereal andino usado para la producción de cerveza y alimentos. Se cultiva en la sierra peruana.',
        'categoria': 'Cereales',
        'temporada': 'Octubre - Diciembre (siembra), Abril - Mayo (cosecha)',
        'clima': 'Frío a templado, 8-20°C. Tolera heladas moderadas.',
        'suelo': 'Franco, bien drenado. pH 5.5-7.0.',
        'riego': 'Cada 7-10 días. Crítico en macollamiento y espigado.',
        'fertilizante': 'NPK 15-10-10. Urea en macollamiento.',
        'nutrientes': 'Nitrógeno (N), Fósforo (P), Potasio (K), Zinc (Zn)',
        'plagas': ['Pulgones', 'Gusano cogollero', 'Trips'],
        'enfermedades': ['Roya de la hoja', 'Mancha reticular', 'Carbón volador'],
        'prevencion': 'Semilla certificada. Rotación de cultivos. Control químico preventivo.',
        'consejos': ['La cebada maltera requiere bajo contenido de proteína.', 'Siembra en surcos para facilitar el riego.', 'Cosecha cuando el grano esté duro y el tallo seco.']
    },
    {
        'id': 'arveja', 'nombre': 'Arveja', 'icono': '🫛',
        'descripcion': 'La arveja es una leguminosa de grano comestible. Se cultiva en la sierra peruana para consumo fresco y seco.',
        'categoria': 'Legumbres',
        'temporada': 'Enero - Abril (sierra), Mayo - Agosto (costa)',
        'clima': 'Templado-frío, 10-20°C.',
        'suelo': 'Franco, suelto. pH 5.5-7.0.',
        'riego': 'Cada 5-7 días. Crítico en floración.',
        'fertilizante': 'NPK 10-20-10. Bajo en nitrógeno (fijan su propio N).',
        'nutrientes': 'Fósforo (P), Potasio (K), Magnesio (Mg), Molibdeno (Mo)',
        'plagas': ['Pulgones', 'Orugas', 'Minador'],
        'enfermedades': ['Oídio', 'Mancha foliar', 'Podredumbre de raíz'],
        'prevencion': 'Rotación larga. Tutoreo para variedades trepadoras. Semilla certificada.',
        'consejos': ['Las variedades trepadoras producen por más tiempo.', 'Cosecha temprano en la mañana para mejor textura.', 'Inocula con Rhizobium para mejorar rendimiento.']
    },
]

CATEGORIAS = sorted(set(g['categoria'] for g in GUIAS))


def get_guias(categoria=None, busqueda=None):
    resultados = GUIAS
    if categoria:
        resultados = [g for g in resultados if g['categoria'] == categoria]
    if busqueda:
        busqueda = busqueda.lower()
        resultados = [g for g in resultados if
                      busqueda in g['nombre'].lower()
                      or busqueda in g['descripcion'].lower()
                      or busqueda in g['categoria'].lower()
                      or any(busqueda in p.lower() for p in g['plagas'])]
    return resultados


def get_categorias():
    return CATEGORIAS


def get_guia_por_id(guias_id):
    for g in GUIAS:
        if g['id'] == guias_id:
            return g
    return None
