"""Modelos Usuario y Analisis con columna imagen

Revision ID: 230b2b675bfe
Revises: 
Create Date: 2026-05-08 12:20:10.786553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230b2b675bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
